### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by wermaxta** [trustedsec/trevorc2#2]
Hi my OS is Linux kali 4.13.0-kali1-amd64 #1 SMP Debian 4.13.4-2kali1 (2017-10-16) x86_64 GNU/Linux
Python 2.7.14 
when i type python trevorc2_server.py i get this 

TrevorC2 - Legitimate Website Covert Channel
Written by: David Kennedy (@HackingDave)
https://www.trustedsec.com
[*] Cloning website: https://www.google.com/
[*] Site cloned successfully.
[*] Starting C2 Server...
[*] Next, enter the command you want the victim to execute.
[*] Client uses random intervals, this may take a few.
Enter the command to execute on victim: Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "trevorc2_server.py", line 225, in main_c2
    http_server.listen(80)
  File "/usr/lib/python2.7/dist-packages/tornado/tcpserver.py", line 142, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/lib/python2.7/dist-packages/tornado/netutil.py", line 196, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

Thank you :)

**Comment by trustedsec** [comment]
Based on the error log, looks like you are already listening on port 80 (probably apache)

error: [Errno 98] Address already in use

Try:

service apache2 stop and re-run.

Let me know if you have any other questions, happy to help!
